files:
  - config/plex/config/Library/Application Support/Plex Media Server/Preferences.xml
  - config/seerr/config/settings.json
  - config/prowlarr/config/Backups/**
  - config/radarr/config/Backups/**
  - config/sonarr/config/Backups/**
  - config/tautulli/config/backups/**
  - config/transmission/config/transmission-home/settings.json
  - etc/nixos/.env
  - etc/nixos/auth/config.yml
  - etc/nixos/backup/credentials.json
